---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: redis
  name: redis-config
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    dir "/data"
    maxmemory 0
    requirepass inspur
    appendonly no
    protected-mode no
  init.sh: |
    
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: redis-secret
# type: Opaque
# data:
#   REDIS_PASS: cm9vdA==
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-svc-nodeport
spec:
  type: NodePort
  ports:
    - port: 6379
      name: redis
      targetPort: 6379
  selector:
    app: redis

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-svc
spec:
  ports:
    - port: 6379
      name: redis
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis  # has to match .spec.template.metadata.labels
  replicas: 1
  template:
    metadata:
      labels:
        app: redis  # has to match .spec.selector.matchLabels
    spec:
      # initContainers:
      # - name: initconfig
      #   image: busybox
      #   command: ["/bin/sh", "-c"]
      #   args:
      #   - 'mkdir -p /data/etc/redis/ && cat  /opt/redis/redis.conf  > /data/etc/redis/redis.conf && sed -i "s/replace-default-auth/${REDIS_PASS}/" /data/etc/redis/redis.conf'
      #   env:
      #   - name: REDIS_PASS
      #     valueFrom:
      #       secretKeyRef:
      #         name: redis-secret
      #         key: REDIS_PASS
      #   volumeMounts:
      #   - mountPath: /data
      #     name: data
      #   - name: config
      #     mountPath: /opt/redis/
        
      containers:
      - name: redis
        image: redis:4.0.14
        command:
        - redis-server
        args:
        - /opt/redis/redis.conf
        # args: ["--requirepass", "$(REDIS_PASS)", "--appendonly", "yes"]
        ports:
          - containerPort: 6379
            name: redis
        env:
        # - name: REDIS_PASS
        #   valueFrom:
        #     secretKeyRef:
        #       name: redis-secret
        #       key: REDIS_PASS
        livenessProbe:
          tcpSocket:
            port: redis
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: redis
          initialDelaySeconds: 30
          periodSeconds: 5
        volumeMounts:
        - mountPath: /data
          name: data
        - name: config
          mountPath: /opt/redis/
        - name: localtime
          mountPath: /etc/localtime
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      volumes:
      - name: config
        configMap:
          name: redis-config
          defaultMode: 420
      - name: data
        hostPath:
          path: /data/redis
      - name: localtime
        hostPath:
          path: /etc/localtime

